[project]
name = "door"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bleak>=1.1.1",
    "pigpio>=1.78",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
