[project]
name = "door"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bleak>=1.1.1",
    "bluepy>=1.3.0",
    "pigpio>=1.78",
]
